replicaCount: 1

image:
  repository: 722124002401.dkr.ecr.ap-south-1.amazonaws.com/lm-lastmiles
  tag: "4.21"
  pullPolicy: Always

service:
  port: 7001

deployment:
  name: lm-lastmile-appd-deployment
  namespace: sd2-lm
  app: lm-lastmilev1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}

imagePullSecrets: []

serviceAccount:
  name: ""

podSecurityContext: {}
securityContext: {}

resources: {}

volumeMounts: []
volumes: []

nodeSelector:
  eks.amazonaws.com/nodegroup: sd2-lastmile-pvt-ng

affinity: {}
tolerations: {}

livenessProbe: {}
readinessProbe: {}

