apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: lm-lastmile-rollout
  namespace: sd2-lm
  labels:
    app: lm-lastmile
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lm-lastmilev1
  template:
    metadata:
      labels:
        app: lm-lastmilev1
    spec:
      containers:
      - name: sd2-lm
        image: 722124002401.dkr.ecr.ap-south-1.amazonaws.com/lm-lastmiles:4.21
        imagePullPolicy: Always
        ports:
        - containerPort: 7001
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
  strategy:
    blueGreen:
      activeService: lm-lastmile-active
      previewService: lm-lastmile-preview
      prePromotionAnalysis:
        templates:
        - templateName: lm-lastmile-analysis
        args:
        - name: service-name
          value: lm-lastmile-preview.default.svc.cluster.local


---
apiVersion: v1
kind: Service
metadata:
  name: lm-lastmile-active
  namespace: sd2-lm
  labels:
    app: lm-lastmile
spec:
  ports:
    - port: 80
      targetPort: 7001
  selector:
    app: lm-lastmilev1

---
apiVersion: v1
kind: Service
metadata:
  name: lm-lastmile-preview
  namespace: sd2-lm
  labels:
    app: lm-lastmile
spec:
  ports:
    - port: 80
      targetPort: 7001
  selector:
    app: lm-lastmilev1


