{{- if eq .Values.strategy "bluegreen" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "realtimeapp.fullname" . }}
  labels:
    app: {{ include "realtimeapp.serviceName" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "realtimeapp.serviceName" . }}
  template:
    metadata:
      labels:
        app: {{ include "realtimeapp.serviceName" . }}
    spec:
      containers:
        - name: realtimeapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: REDISHOST
              value: "redisapp:6379"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          ports:
            - containerPort: 8080
  strategy:
    blueGreen:
      activeService: {{ .Values.blueGreen.activeService }}
      previewService: {{ .Values.blueGreen.previewService }}
      prePromotionAnalysis:
        templates:
        - templateName: realtime-analysis
        args:
        - name: service-name
          value: {{ .Values.blueGreen.previewService }}
{{- end }}
