apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}

