apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx
  namespace: default
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
  - repoURL: 'https://ot-container-kit.github.io/helm-charts'
    chart: microservice
    targetRevision: 0.1.5
    helm:
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://github.com/shristiopstree/helm-nginx-poc.git'
    targetRevision: main
    ref: values
